LabeledAsserts.dfyp(25,11): Error: assertion might not hold
LabeledAsserts.dfyp(27,18): Error: assertion might not hold
LabeledAsserts.dfyp(28,18): Error: assertion might not hold
LabeledAsserts.dfyp(29,15): Error: assertion might not hold
LabeledAsserts.dfyp(32,11): Error: assertion might not hold
LabeledAsserts.dfyp(162,17): Error: assertion might not hold
LabeledAsserts.dfyp(172,15): Error: assertion might not hold
LabeledAsserts.dfyp(189,19): Error: assertion might not hold
LabeledAsserts.dfyp(193,13): Error: assertion might not hold
LabeledAsserts.dfyp(16,11): Error: assertion might not hold
LabeledAsserts.dfyp(42,18): Error: assertion might not hold
LabeledAsserts.dfyp(43,13): Error: assertion might not hold
LabeledAsserts.dfyp(91,13): Error: assertion might not hold
LabeledAsserts.dfyp(105,13): Error: assertion might not hold
LabeledAsserts.dfyp(107,13): Error: assertion might not hold
LabeledAsserts.dfyp(128,15): Error: assertion might not hold
LabeledAsserts.dfyp(142,19): Error: assertion might not hold
LabeledAsserts.dfyp(146,13): Error: assertion might not hold
LabeledAsserts.dfyp(206,20): Error: assertion might not hold
LabeledAsserts.dfyp(207,15): Error: assertion might not hold
LabeledAsserts.dfyp(211,15): Error: assertion might not hold
LabeledAsserts.dfyp(224,20): Error: assertion might not hold
LabeledAsserts.dfyp(226,11): Error: assertion might not hold
LabeledAsserts.dfyp(232,11): Error: assertion might not hold
LabeledAsserts.dfyp(252,6): Error: the calculation step between the previous line and this line might not hold
LabeledAsserts.dfyp(265,9): Error: assertion might not hold

Dafny program verifier finished with 11 verified, 26 errors
